### ISSUE TITLE
Theory of the project

### ISSUE THREAD

**Issue by agraharipranjul** [yashshah2609/Emotion-Based-music-player#2]
Sir.. I want to know which algorithms were used and what is flow of the project ..
If you have any report or papers related to this project ....please sir mail me  agraharipranjul@gmail.com 
it would be great help for me .

**Comment by yashshah2609** [comment]
I have sent report of this project to your mail-id , if you have any queries regarding anything in project just reply me on the mail by which I have sent you report. Sorry 4 the late reply.

**Comment by starnger** [comment]
Hello Yash, can you please send this project report to my email id thankimayank23@gmail.com
I just wanted to know the project clearly.  
Thank you

**Comment by yashshah2609** [comment]
Hello mayank,
       I will send you by noon tomorrow.
Thanks
Yash Shah

**Comment by Pranavi-Peddoju** [comment]
Hey
Even I want to know which algorithms were used and what is flow of the project ..
If you have any report or papers related to this project ....please sir mail me
pranavipeddoju@gmail.com 
Please,
This would help us for our project which is similar to this
